# Generated by Django 5.0 on 2023-12-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supplier_profile',
            fields=[
                ('supplier_name', models.TextField(primary_key=True, serialize=False)),
                ('supplier_address', models.TextField(blank=True)),
                ('contact_person', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
