# Generated by Django 5.0 on 2023-11-15 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0004_shipping_info_cosmic_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_order',
            name='ref_no',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='order_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_vat', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement', models.TextField(blank=True, null=True)),
                ('order_no', models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmic.cosmic_order')),
            ],
        ),
    ]
