# Generated by Django 5.0 on 2023-11-17 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0005_cosmic_order_ref_no_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_order',
            name='remaining',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='supplier_name',
            field=models.ForeignKey(db_column='supplier_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_supplier', to='cosmic.supplier_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
