# Generated by Django 5.0 on 2023-11-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0006_cosmic_order_remaining_cosmic_order_supplier_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmic_order',
            name='total_price',
        ),
    ]
