# Generated by Django 5.0 on 2023-11-27 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0007_remove_cosmic_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='total_price',
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='consignee',
            field=models.ForeignKey(blank=True, db_column='consignee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consignee', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='freight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='notify_party',
            field=models.ForeignKey(blank=True, db_column='notify_party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notify_party_one', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='notify_party2',
            field=models.ForeignKey(blank=True, db_column='notify_party2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_related_to_bank', to='cosmic.customer_profile'),
        ),
    ]
