# Generated by Django 5.0 on 2023-12-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0009_remove_shipping_info_pr_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_vat', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement', models.TextField(blank=True, null=True)),
                ('net_weight', models.FloatField(blank=True, null=True)),
                ('gross_weight', models.FloatField(blank=True, null=True)),
                ('bags', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipping_info',
            name='country_of_origin',
        ),
        migrations.RemoveField(
            model_name='shipping_info',
            name='final_destination',
        ),
        migrations.RemoveField(
            model_name='shipping_info',
            name='port_of_discharge',
        ),
        migrations.RemoveField(
            model_name='shipping_info',
            name='port_of_loading',
        ),
        migrations.AddField(
            model_name='cosmic_order',
            name='freight_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
