# Generated by Django 5.0 on 2023-12-08 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0010_invoice_item_remove_shipping_info_country_of_origin_and_more'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='shipping_info',
            name='unique_no',
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='invoice_num',
            field=models.TextField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='order_no',
            field=models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmic.cosmic_order'),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='reference_no',
            field=models.TextField(blank=True, null=True),
        ),
    ]
