# Generated by Django 5.0 on 2023-12-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0011_shipping_info_invoice_num_shipping_info_order_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_info',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='invoice_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='lading_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='packing_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='total_bags',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipping_info',
            name='waybill_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
