# Generated by Django 5.0 on 2023-12-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0012_shipping_info_final_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='item_codes',
            fields=[
                ('hs_code', models.TextField(primary_key=True, serialize=False)),
                ('item_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cosmic_purchase',
            name='total_price',
        ),
    ]
