# Generated by Django 5.0 on 2024-02-09 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0013_item_codes_remove_cosmic_purchase_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_purchase',
            name='consignee',
            field=models.ForeignKey(blank=True, db_column='consignee', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_consignee', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='country_of_origin',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='customer_name',
            field=models.ForeignKey(db_column='customer_name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_related_to_customer', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='final_destination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='freight',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='freight_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='notify_party',
            field=models.ForeignKey(blank=True, db_column='notify_party', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_notify_party_one', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='notify_party2',
            field=models.ForeignKey(blank=True, db_column='notify_party2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_related_to_bank', to='cosmic.customer_profile'),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='port_of_discharge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='port_of_loading',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='ref_no',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cosmic_purchase',
            name='total_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
