# Generated by Django 5.0 on 2024-02-09 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0014_cosmic_purchase_consignee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='purchase_item',
            fields=[
                ('id_numeric', models.AutoField(primary_key=True, serialize=False)),
                ('hs_code', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField(blank=True, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('before_vat', models.FloatField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('measurement', models.TextField(blank=True, null=True)),
                ('purchase_no', models.ForeignKey(blank=True, db_column='order_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmic.cosmic_order')),
            ],
        ),
    ]
