# Generated by Django 5.0 on 2024-03-20 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0016_cosmic_purchase_remaining_purchase_item_remaining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_item',
            name='invoice_num',
            field=models.ForeignKey(blank=True, db_column='invoice_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmic.shipping_info'),
        ),
        migrations.AlterField(
            model_name='item_codes',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item_codes',
            name='hs_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
