# Generated by Django 5.0 on 2024-04-09 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0018_alter_shipping_info_container_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_order',
            name='status_remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
