# Generated by Django 5.0 on 2024-04-11 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmic", "0019_cosmic_order_status_remark"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer_profile",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
