# Generated by Django 5.0 on 2024-04-11 11:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmic", "0020_customer_profile_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier_profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
