# Generated by Django 5.0 on 2024-06-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0022_cosmic_purchase_status_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        # migrations.AddField(
        #     model_name='cosmic_purchase',
        #     name='conditions',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
