# Generated by Django 5.0 on 2024-06-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0023_income_cosmic_purchase_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='cosmic_income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='income',
        ),
    ]
