# Generated by Django 5.0 on 2024-06-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0024_cosmic_income_delete_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmic_income',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_income',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_income',
            name='payment_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_income',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_income',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cosmic_income',
            name='serial_no',
            field=models.TextField(null=True),
        ),
    ]
