# Generated by Django 5.0 on 2024-06-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0026_cosmic_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmic_expense',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
