# Generated by Django 5.0 on 2024-06-10 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0027_alter_cosmic_expense_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cosmic_expense',
            old_name='file',
            new_name='attachement',
        ),
    ]
