# Generated by Django 5.0 on 2024-06-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0028_rename_file_cosmic_expense_attachement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmic_expense',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
