# Generated by Django 5.0 on 2024-06-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0029_alter_cosmic_expense_attachement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cosmic_expense',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cosmic_income',
            name='id',
        ),
        # migrations.AddField(
        #     model_name='cosmic_purchase',
        #     name='conditions',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AlterField(
            model_name='cosmic_expense',
            name='serial_no',
            field=models.TextField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cosmic_income',
            name='serial_no',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
