# Generated by Django 5.0 on 2024-07-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0030_remove_cosmic_expense_id_remove_cosmic_income_id_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cosmic_purchase',
        #     name='conditions',
        #     field=models.TextField(blank=True, null=True),
        # ),
    ]
