# Generated by Django 5.0 on 2024-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0031_cosmic_purchase_conditions'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cosmic_purchase',
        #     name='conditions',
        #     field=models.TextField(blank=True, null=True),
        # ),
        migrations.AddField(
            model_name='purchase_item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
