# Generated by Django 5.0 on 2024-07-29 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0033_remove_purchase_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='grn',
            fields=[
                ('GRN_no', models.TextField(primary_key=True, serialize=False)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('recieved_from', models.TextField(blank=True, null=True)),
                ('transporter_name', models.TextField(blank=True, null=True)),
                ('truck_no', models.TextField(blank=True, null=True)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('store_keeper', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='grnitem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, null=True)),
                ('GRN_no', models.ForeignKey(blank=True, db_column='GRN_no', null=True, on_delete=django.db.models.deletion.CASCADE, to='cosmic.grn')),
            ],
        ),
    ]
