# Generated by Django 5.0 on 2024-07-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0033_remove_purchase_item_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('GRN_no', models.TextField(primary_key=True, serialize=False)),
                ('grn_date', models.DateField(blank=True, null=True)),
                ('recieved_from', models.TextField(blank=True, null=True)),
                ('transporter_name', models.TextField(blank=True, null=True)),
                ('truck_no', models.TextField(blank=True, null=True)),
                ('store_name', models.TextField(blank=True, null=True)),
                ('store_keeper', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'GRN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
