# Generated by Django 5.0 on 2024-07-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0036_cosmic_grn_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='cosmic_delivery',
            fields=[
                ('delivery_number', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_date', models.DateField(blank=True)),
                ('delivery_quantity', models.IntegerField(blank=True)),
                ('truck_number', models.TextField(blank=True, null=True)),
                ('driver_name', models.TextField(blank=True, null=True)),
                ('recipient_name', models.TextField(blank=True, null=True)),
                ('delivery_comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cosmic_delivery',
                'managed': False,
            },
        ),
    ]
