# Generated by Django 5.0 on 2024-07-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cosmic', '0037_cosmic_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cosmic_expense',
        ),
        migrations.DeleteModel(
            name='cosmic_income',
        ),
    ]
