# Generated by Django 5.0 on 2024-12-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cosmic", "0038_delete_cosmic_expense_delete_cosmic_income"),
    ]

    operations = [
        migrations.AddField(
            model_name="cosmic_purchase",
            name="insurance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
